import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "de";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.insights": "Insights",
    "nav.events": "Events",
    "nav.partners": "Partners",
    "nav.cta": "Book Free Consultation",
    "hero.headline": "Your Financial Life in Germany — Simplified",
    "hero.subheadline":
      "Insurance, investments, and long-term planning tailored for expats.",
    "hero.cta": "Start Your Free Financial Roadmap",
    "hero.subcta": "No commitment. No upfront cost.",
    "trust.cost": "No Upfront Cost",
    "trust.guidance": "Transparent Guidance",
    "trust.expat": "Tailored for Expats",
    "trust.clients": "2,400+ Expats Helped",
    "roadmap.title": "Your Expat Financial Roadmap",
    "roadmap.subtitle":
      "A clear path from arrival to long-term financial freedom in Germany.",
    "path.title": "How It Works",
    "path.subtitle":
      "Our proven 5-step process from your first consultation to financial independence.",
    "case.title": "Real Expat Story",
    "case.subtitle": "How Ahmed went from financial chaos to clarity in 6 months.",
    "etf.title": "ETF Comparison Dashboard",
    "etf.subtitle":
      "Compare top-performing ETFs available in Germany — beginner to advanced.",
    "footer.tagline": "Simplifying financial life for expats in Germany.",
    "sticky.cta": "Book Free Consultation",
    "contact.title": "Book Free Consultation",
    "contact.subtitle": "Start your journey to financial clarity in Germany.",
    "contact.name": "Full Name",
    "contact.email": "Email Address",
    "contact.topic": "What's this about?",
    "contact.topicGeneral": "General financial roadmap",
    "contact.topicETF": "ETF portfolio",
    "contact.topicTax": "Tax optimization",
    "contact.topicInsurance": "Insurance (BU, Haftpflicht, Rechtsschutz)",
    "contact.topicRetirement": "Retirement / Altersvorsorge",
    "contact.topicCorporate": "Corporate partnership",
    "contact.topicEvent": "Event registration",
    "contact.topicOther": "Other",
    "contact.phone": "Phone Number",
    "contact.message": "Message",
    "contact.placeholder": "Tell us about your financial goals...",
    "contact.submit": "Send Message",
    "contact.sending": "Sending...",
    "contact.success": "Message Sent!",
    "contact.successMessage": "We'll get back to you within 24 hours.",
    "contact.privacy": "We use your details only to contact you about your consultation. No spam, no sharing.",

    // Footer
    "footer.services": "Services",
    "footer.resources": "Resources",
    "footer.contact": "Contact",
    "footer.healthInsurance": "Health Insurance",
    "footer.retirementPlanning": "Retirement Planning",
    "footer.etfPortfolio": "ETF Portfolio",
    "footer.buInsurance": "BU Insurance",
    "footer.taxOptimization": "Tax Optimization",
    "footer.legalProtection": "Legal Protection",
    "footer.insightsHub": "Insights Hub",
    "footer.expatEvents": "Expat Events",
    "footer.etfGuide": "ETF Guide",
    "footer.taxCalculator": "Tax Calculator",
    "footer.financialGlossary": "Financial Glossary",
    "footer.careersLink": "Careers",
    "footer.careers": "Careers",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.imprint": "Imprint",
    "footer.copyright": "© 2026 Expatrum GmbH. All rights reserved. Not a licensed financial advisor.",

    // ETF Dashboard
    "etf.liveIntelligence": "Live ETF Intelligence",
    "etf.fund": "FUND",
    "etf.risk": "RISK",
    "etf.return5y": "5Y RETURN",
    "etf.ter": "TER",
    "etf.selectedFund": "SELECTED FUND",
    "etf.terFees": "TER (fees)",
    "etf.riskLevel": "Risk Level",
    "etf.bestFor": "Best For",
    "etf.isin": "ISIN",
    "etf.disclaimer": "Past performance is not indicative of future results. Educational purposes only.",
    "etf.ctaTitle": "Get Your Personalized ETF Portfolio",
    "etf.ctaSubtitle": "Tailored to your risk profile & goals",

    // Plan Path
    "path.process": "Our Process",
    "path.step1Label": "Input",
    "path.step1Description": "Tell us about your income, goals, and current situation.",
    "path.step1Outcome": "Personalized profile created",
    "path.step2Label": "Analysis",
    "path.step2Description": "We assess your financial gaps, risks, and opportunities.",
    "path.step2Outcome": "Full gap analysis report",
    "path.step3Label": "Strategy",
    "path.step3Description": "A tailored roadmap built around your goals and timeline.",
    "path.step3Outcome": "Clear ETF allocation + insurance plan",
    "path.step4Label": "Implementation",
    "path.step4Description": "We walk you through every setup step — side by side.",
    "path.step4Outcome": "Accounts, policies & portfolios live",
    "path.step5Label": "Optimization",
    "path.step5Description": "Annual reviews to adapt your plan as life evolves.",
    "path.step5Outcome": "Always-optimized financial life",

    // Partners
    "partners.badge": "Trusted Network",
    "partners.title": "Our Partners",
    "partners.subtitle": "We work with Germany's leading insurance providers and financial institutions to bring you the best solutions for your expat journey.",
    "partners.insuranceTitle": "Insurance Partners",
    "partners.bankingTitle": "Banking & Investment Partners",
    "partners.ctaTitle": "Ready to get started?",
    "partners.ctaSubtitle": "Let us connect you with the right partners for your financial goals.",
    "partners.ctaButton": "Book Free Consultation",

    // Careers
    "careers.badge": "Join Our Team",
    "careers.title": "Careers at Expatrum",
    "careers.subtitle": "Help us build the future of expat financial guidance in Germany. We're looking for passionate individuals who want to make a real impact.",
    "careers.value1Title": "Expat-Centric Culture",
    "careers.value1Description": "We understand the expat experience because we live it. Join a diverse, international team.",
    "careers.value2Title": "Growth & Impact",
    "careers.value2Description": "Work on meaningful projects that directly improve expats' financial lives in Germany.",
    "careers.value3Title": "Flexible & Remote-First",
    "careers.value3Description": "Work from anywhere in Germany with flexible hours that fit your lifestyle.",
    "careers.openPositions": "Open Positions",
    "careers.noOpenings": "We don't have any open positions at the moment, but we're always looking for talented individuals. Feel free to send us your CV.",
    "careers.ctaTitle": "Don't see the right role?",
    "careers.ctaSubtitle": "Send us your CV and tell us how you'd like to contribute to Expatrum's mission.",
    "careers.ctaButton": "Send Your CV",

    // Career Application Form
    "careerApp.heroTitle": "Join the Expatrum Team",
    "careerApp.heroSubtitle": "Help us redefine financial clarity and support for expats. Explore career opportunities and become part of a fast-growing, impact-driven team.",
    "careerApp.section1Title": "Personal Information",
    "careerApp.section1Subtitle": "Tell us about yourself",
    "careerApp.fullName": "Full Name",
    "careerApp.email": "Email Address",
    "careerApp.phone": "Phone Number",
    "careerApp.country": "Country of Residence",
    "careerApp.city": "City",
    "careerApp.workAuth": "Work Authorization / Visa Status",
    "careerApp.section2Title": "Professional Information",
    "careerApp.section2Subtitle": "Share your professional background",
    "careerApp.position": "Position Applying For",
    "careerApp.yearsExp": "Years of Experience",
    "careerApp.currentTitle": "Current Job Title",
    "careerApp.currentEmployer": "Current Employer",
    "careerApp.expertise": "Area of Expertise (select all that apply)",
    "careerApp.section3Title": "Portfolio & Professional Profiles",
    "careerApp.section3Subtitle": "Optional: Share your professional presence",
    "careerApp.linkedin": "LinkedIn Profile URL",
    "careerApp.portfolio": "Portfolio Website",
    "careerApp.otherProfile": "Other Profile (GitHub, Behance, Dribbble)",
    "careerApp.section4Title": "Documents Upload",
    "careerApp.section4Subtitle": "Upload your application documents",
    "careerApp.cv": "Upload CV / Resume",
    "careerApp.coverLetter": "Upload Cover Letter (optional)",
    "careerApp.portfolioDoc": "Upload Portfolio (optional)",
    "careerApp.uploadFile": "Click to upload or drag and drop",
    "careerApp.section5Title": "Motivation & Availability",
    "careerApp.section5Subtitle": "Tell us why you want to join",
    "careerApp.motivation": "Why do you want to join Expatrum?",
    "careerApp.motivationPlaceholder": "Share what excites you about this opportunity...",
    "careerApp.greatFit": "What makes you a great fit?",
    "careerApp.greatFitPlaceholder": "Tell us about your unique strengths and experience...",
    "careerApp.startDate": "Earliest Start Date",
    "careerApp.employmentType": "Employment Type Preference",
    "careerApp.section6Title": "Consent & Privacy",
    "careerApp.consent1": "I confirm that the information provided is accurate",
    "careerApp.consent2": "I agree to the privacy policy",
    "careerApp.consent3": "I consent to being contacted regarding my application",
    "careerApp.secureInfo": "Your information is securely handled and will only be used for recruitment purposes.",
    "careerApp.submit": "Submit Application",
    "careerApp.submitting": "Submitting...",
    "careerApp.successTitle": "Application Submitted Successfully!",
    "careerApp.successMessage": "Thank you for applying to Expatrum. We've received your application and will review it carefully. If your profile matches our requirements, we'll reach out to you within 1-2 weeks.",
    "careerApp.backToCareers": "Back to Careers",
    "careerApp.whyJoinTitle": "Why Join Expatrum?",
    "careerApp.benefit1Title": "International Team",
    "careerApp.benefit1Desc": "Work with talented professionals from around the world who understand the expat journey.",
    "careerApp.benefit2Title": "Real Impact",
    "careerApp.benefit2Desc": "Help thousands of expats navigate financial complexity and build secure futures.",
    "careerApp.benefit3Title": "Work-Life Balance",
    "careerApp.benefit3Desc": "Flexible hours, remote work options, and a culture that values your wellbeing.",
    "careerApp.benefit4Title": "Growth Opportunities",
    "careerApp.benefit4Desc": "Continuous learning, professional development, and clear career progression paths.",
    "careerApp.valuesTitle": "Our Core Values",
    "careerApp.value1": "Trust & Transparency",
    "careerApp.value2": "Innovation & Excellence",
    "careerApp.value3": "Empathy & Support",
    "careerApp.faqTitle": "Frequently Asked Questions",
    "careerApp.faq1Q": "How long does the hiring process take?",
    "careerApp.faq1A": "Our hiring process typically takes 2-4 weeks from application to final decision. We'll keep you updated at every stage.",
    "careerApp.faq2Q": "Do you sponsor work visas?",
    "careerApp.faq2A": "Yes, we sponsor work visas for exceptional candidates. Please mention your visa requirements in your application.",
    "careerApp.faq3Q": "Is remote work possible?",
    "careerApp.faq3A": "Yes, we offer remote and hybrid work options for most positions. Location flexibility is part of our culture.",
    "careerApp.faq4Q": "What benefits do you offer?",
    "careerApp.faq4A": "We offer competitive salary, health insurance, retirement plans, professional development budget, and flexible work arrangements.",
  },
  de: {
    "nav.home": "Startseite",
    "nav.services": "Leistungen",
    "nav.insights": "Einblicke",
    "nav.events": "Veranstaltungen",
    "nav.partners": "Partner",
    "nav.cta": "Kostenlose Beratung buchen",
    "hero.headline": "Ihr Finanzleben in Deutschland — vereinfacht",
    "hero.subheadline":
      "Versicherungen, Investitionen und Langzeitplanung für Expats.",
    "hero.cta": "Kostenlose Finanzberatung starten",
    "hero.subcta": "Kein Aufwand. Keine Vorabkosten.",
    "trust.cost": "Keine Vorabkosten",
    "trust.guidance": "Transparente Beratung",
    "trust.expat": "Für Expats maßgeschneidert",
    "trust.clients": "2.400+ Expats beraten",
    "roadmap.title": "Ihr Expat-Finanzfahrplan",
    "roadmap.subtitle":
      "Ein klarer Weg von der Ankunft zur finanziellen Freiheit in Deutschland.",
    "path.title": "So funktioniert es",
    "path.subtitle":
      "Unser bewährter 5-Schritte-Prozess zur finanziellen Unabhängigkeit.",
    "case.title": "Echte Expat-Geschichte",
    "case.subtitle":
      "Wie Ahmed in 6 Monaten von finanziellem Chaos zur Klarheit kam.",
    "etf.title": "ETF-Vergleichs-Dashboard",
    "etf.subtitle":
      "Vergleichen Sie die leistungsstärksten ETFs in Deutschland.",
    "footer.tagline": "Vereinfachung des Finanzlebens für Expats in Deutschland.",
    "sticky.cta": "Kostenlose Beratung buchen",
    "contact.title": "Kostenlose Beratung buchen",
    "contact.subtitle": "Beginnen Sie Ihre Reise zur finanziellen Klarheit in Deutschland.",
    "contact.name": "Vollständiger Name",
    "contact.email": "E-Mail-Adresse",
    "contact.topic": "Worum geht es?",
    "contact.topicGeneral": "Allgemeiner Finanzfahrplan",
    "contact.topicETF": "ETF-Portfolio",
    "contact.topicTax": "Steueroptimierung",
    "contact.topicInsurance": "Versicherung (BU, Haftpflicht, Rechtsschutz)",
    "contact.topicRetirement": "Ruhestand / Altersvorsorge",
    "contact.topicCorporate": "Unternehmenspartnerschaft",
    "contact.topicEvent": "Veranstaltungsregistrierung",
    "contact.topicOther": "Andere",
    "contact.phone": "Telefonnummer",
    "contact.message": "Nachricht",
    "contact.placeholder": "Erzählen Sie uns von Ihren finanziellen Zielen...",
    "contact.submit": "Nachricht senden",
    "contact.sending": "Wird gesendet...",
    "contact.success": "Nachricht gesendet!",
    "contact.successMessage": "Wir melden uns innerhalb von 24 Stunden bei Ihnen.",
    "contact.privacy": "Wir verwenden Ihre Daten nur, um Sie bezüglich Ihrer Beratung zu kontaktieren. Kein Spam, keine Weitergabe.",

    // Footer
    "footer.services": "Leistungen",
    "footer.resources": "Ressourcen",
    "footer.contact": "Kontakt",
    "footer.healthInsurance": "Krankenversicherung",
    "footer.retirementPlanning": "Altersvorsorge",
    "footer.etfPortfolio": "ETF-Portfolio",
    "footer.buInsurance": "BU-Versicherung",
    "footer.taxOptimization": "Steueroptimierung",
    "footer.legalProtection": "Rechtsschutz",
    "footer.insightsHub": "Insights Hub",
    "footer.expatEvents": "Expat-Veranstaltungen",
    "footer.etfGuide": "ETF-Leitfaden",
    "footer.taxCalculator": "Steuerrechner",
    "footer.financialGlossary": "Finanzglossar",
    "footer.careersLink": "Karriere",
    "footer.careers": "Karriere",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.imprint": "Impressum",
    "footer.copyright": "© 2026 Expatrum GmbH. Alle Rechte vorbehalten. Kein lizenzierter Finanzberater.",

    // ETF Dashboard
    "etf.liveIntelligence": "Live-ETF-Intelligenz",
    "etf.fund": "FONDS",
    "etf.risk": "RISIKO",
    "etf.return5y": "5J RENDITE",
    "etf.ter": "TER",
    "etf.selectedFund": "AUSGEWÄHLTER FONDS",
    "etf.terFees": "TER (Gebühren)",
    "etf.riskLevel": "Risikoniveau",
    "etf.bestFor": "Geeignet für",
    "etf.isin": "ISIN",
    "etf.disclaimer": "Die vergangene Wertentwicklung ist kein verlässlicher Indikator für künftige Ergebnisse. Nur zu Bildungszwecken.",
    "etf.ctaTitle": "Erhalten Sie Ihr personalisiertes ETF-Portfolio",
    "etf.ctaSubtitle": "Auf Ihr Risikoprofil & Ihre Ziele zugeschnitten",

    // Plan Path
    "path.process": "Unser Prozess",
    "path.step1Label": "Eingabe",
    "path.step1Description": "Erzählen Sie uns von Ihrem Einkommen, Zielen und aktueller Situation.",
    "path.step1Outcome": "Personalisiertes Profil erstellt",
    "path.step2Label": "Analyse",
    "path.step2Description": "Wir bewerten Ihre finanziellen Lücken, Risiken und Chancen.",
    "path.step2Outcome": "Vollständiger Lückenanalysebericht",
    "path.step3Label": "Strategie",
    "path.step3Description": "Ein maßgeschneiderter Fahrplan basierend auf Ihren Zielen und Zeitplan.",
    "path.step3Outcome": "Klare ETF-Allokation + Versicherungsplan",
    "path.step4Label": "Umsetzung",
    "path.step4Description": "Wir führen Sie durch jeden Schritt — Seite an Seite.",
    "path.step4Outcome": "Konten, Policen & Portfolios live",
    "path.step5Label": "Optimierung",
    "path.step5Description": "Jährliche Überprüfungen, um Ihren Plan anzupassen.",
    "path.step5Outcome": "Stets optimiertes Finanzleben",

    // Partners
    "partners.badge": "Vertrauensnetzwerk",
    "partners.title": "Unsere Partner",
    "partners.subtitle": "Wir arbeiten mit Deutschlands führenden Versicherungsanbietern und Finanzinstituten zusammen, um Ihnen die besten Lösungen für Ihre Expat-Reise zu bieten.",
    "partners.insuranceTitle": "Versicherungspartner",
    "partners.bankingTitle": "Bank- und Investitionspartner",
    "partners.ctaTitle": "Bereit loszulegen?",
    "partners.ctaSubtitle": "Lassen Sie uns Sie mit den richtigen Partnern für Ihre finanziellen Ziele verbinden.",
    "partners.ctaButton": "Kostenlose Beratung buchen",

    // Careers
    "careers.badge": "Werde Teil unseres Teams",
    "careers.title": "Karriere bei Expatrum",
    "careers.subtitle": "Helfen Sie uns, die Zukunft der Finanzberatung für Expats in Deutschland zu gestalten. Wir suchen leidenschaftliche Menschen, die einen echten Unterschied machen wollen.",
    "careers.value1Title": "Expat-zentrierte Kultur",
    "careers.value1Description": "Wir verstehen die Expat-Erfahrung, weil wir sie leben. Werde Teil eines vielfältigen, internationalen Teams.",
    "careers.value2Title": "Wachstum & Wirkung",
    "careers.value2Description": "Arbeite an bedeutungsvollen Projekten, die das Finanzleben von Expats in Deutschland direkt verbessern.",
    "careers.value3Title": "Flexibel & Remote-First",
    "careers.value3Description": "Arbeite von überall in Deutschland mit flexiblen Arbeitszeiten, die zu deinem Lebensstil passen.",
    "careers.openPositions": "Offene Stellen",
    "careers.noOpenings": "Wir haben derzeit keine offenen Stellen, suchen aber immer nach talentierten Menschen. Senden Sie uns gerne Ihren Lebenslauf.",
    "careers.ctaTitle": "Passende Stelle nicht dabei?",
    "careers.ctaSubtitle": "Senden Sie uns Ihren Lebenslauf und erzählen Sie uns, wie Sie zur Mission von Expatrum beitragen möchten.",
    "careers.ctaButton": "Lebenslauf senden",

    // Career Application Form
    "careerApp.heroTitle": "Werde Teil des Expatrum-Teams",
    "careerApp.heroSubtitle": "Helfen Sie uns, finanzielle Klarheit und Unterstützung für Expats neu zu definieren. Entdecken Sie Karrieremöglichkeiten und werden Sie Teil eines schnell wachsenden, wirkungsorientierten Teams.",
    "careerApp.section1Title": "Persönliche Informationen",
    "careerApp.section1Subtitle": "Erzählen Sie uns von sich",
    "careerApp.fullName": "Vollständiger Name",
    "careerApp.email": "E-Mail-Adresse",
    "careerApp.phone": "Telefonnummer",
    "careerApp.country": "Wohnsitzland",
    "careerApp.city": "Stadt",
    "careerApp.workAuth": "Arbeitserlaubnis / Visumsstatus",
    "careerApp.section2Title": "Berufliche Informationen",
    "careerApp.section2Subtitle": "Teilen Sie Ihren beruflichen Hintergrund",
    "careerApp.position": "Position, für die Sie sich bewerben",
    "careerApp.yearsExp": "Jahre Berufserfahrung",
    "careerApp.currentTitle": "Aktuelle Berufsbezeichnung",
    "careerApp.currentEmployer": "Aktueller Arbeitgeber",
    "careerApp.expertise": "Fachgebiet (alle zutreffenden auswählen)",
    "careerApp.section3Title": "Portfolio & Berufliche Profile",
    "careerApp.section3Subtitle": "Optional: Teilen Sie Ihre berufliche Präsenz",
    "careerApp.linkedin": "LinkedIn-Profil-URL",
    "careerApp.portfolio": "Portfolio-Website",
    "careerApp.otherProfile": "Anderes Profil (GitHub, Behance, Dribbble)",
    "careerApp.section4Title": "Dokumente hochladen",
    "careerApp.section4Subtitle": "Laden Sie Ihre Bewerbungsunterlagen hoch",
    "careerApp.cv": "Lebenslauf hochladen",
    "careerApp.coverLetter": "Anschreiben hochladen (optional)",
    "careerApp.portfolioDoc": "Portfolio hochladen (optional)",
    "careerApp.uploadFile": "Klicken Sie zum Hochladen oder ziehen Sie die Datei hierher",
    "careerApp.section5Title": "Motivation & Verfügbarkeit",
    "careerApp.section5Subtitle": "Sagen Sie uns, warum Sie beitreten möchten",
    "careerApp.motivation": "Warum möchten Sie bei Expatrum arbeiten?",
    "careerApp.motivationPlaceholder": "Teilen Sie uns mit, was Sie an dieser Gelegenheit begeistert...",
    "careerApp.greatFit": "Was macht Sie zur idealen Besetzung?",
    "careerApp.greatFitPlaceholder": "Erzählen Sie uns von Ihren einzigartigen Stärken und Erfahrungen...",
    "careerApp.startDate": "Frühestes Startdatum",
    "careerApp.employmentType": "Bevorzugter Beschäftigungstyp",
    "careerApp.section6Title": "Einwilligung & Datenschutz",
    "careerApp.consent1": "Ich bestätige, dass die angegebenen Informationen korrekt sind",
    "careerApp.consent2": "Ich stimme der Datenschutzerklärung zu",
    "careerApp.consent3": "Ich stimme zu, bezüglich meiner Bewerbung kontaktiert zu werden",
    "careerApp.secureInfo": "Ihre Informationen werden sicher behandelt und nur für Rekrutierungszwecke verwendet.",
    "careerApp.submit": "Bewerbung absenden",
    "careerApp.submitting": "Wird gesendet...",
    "careerApp.successTitle": "Bewerbung erfolgreich eingereicht!",
    "careerApp.successMessage": "Vielen Dank für Ihre Bewerbung bei Expatrum. Wir haben Ihre Bewerbung erhalten und werden sie sorgfältig prüfen. Wenn Ihr Profil unseren Anforderungen entspricht, werden wir uns innerhalb von 1-2 Wochen bei Ihnen melden.",
    "careerApp.backToCareers": "Zurück zu Karriere",
    "careerApp.whyJoinTitle": "Warum bei Expatrum arbeiten?",
    "careerApp.benefit1Title": "Internationales Team",
    "careerApp.benefit1Desc": "Arbeiten Sie mit talentierten Fachleuten aus der ganzen Welt, die die Expat-Reise verstehen.",
    "careerApp.benefit2Title": "Echte Wirkung",
    "careerApp.benefit2Desc": "Helfen Sie Tausenden von Expats, finanzielle Komplexität zu bewältigen und sichere Zukünfte aufzubauen.",
    "careerApp.benefit3Title": "Work-Life-Balance",
    "careerApp.benefit3Desc": "Flexible Arbeitszeiten, Remote-Optionen und eine Kultur, die Ihr Wohlbefinden schätzt.",
    "careerApp.benefit4Title": "Wachstumschancen",
    "careerApp.benefit4Desc": "Kontinuierliches Lernen, berufliche Entwicklung und klare Karrierepfade.",
    "careerApp.valuesTitle": "Unsere Grundwerte",
    "careerApp.value1": "Vertrauen & Transparenz",
    "careerApp.value2": "Innovation & Exzellenz",
    "careerApp.value3": "Empathie & Unterstützung",
    "careerApp.faqTitle": "Häufig gestellte Fragen",
    "careerApp.faq1Q": "Wie lange dauert der Einstellungsprozess?",
    "careerApp.faq1A": "Unser Einstellungsprozess dauert in der Regel 2-4 Wochen von der Bewerbung bis zur endgültigen Entscheidung. Wir halten Sie in jeder Phase auf dem Laufenden.",
    "careerApp.faq2Q": "Sponsern Sie Arbeitsvisa?",
    "careerApp.faq2A": "Ja, wir sponsern Arbeitsvisa für außergewöhnliche Kandidaten. Bitte geben Sie Ihre Visumsanforderungen in Ihrer Bewerbung an.",
    "careerApp.faq3Q": "Ist Remote-Arbeit möglich?",
    "careerApp.faq3A": "Ja, wir bieten Remote- und Hybrid-Arbeitsoptionen für die meisten Positionen an. Standortflexibilität ist Teil unserer Kultur.",
    "careerApp.faq4Q": "Welche Vorteile bieten Sie?",
    "careerApp.faq4A": "Wir bieten wettbewerbsfähige Gehälter, Krankenversicherung, Altersvorsorge, Budget für berufliche Entwicklung und flexible Arbeitsregelungen.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("en");
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
